f2fs-tools: fix build failure on O-MR1
This patch fixes this in O-MR1.

undefined reference to `android::base::StringPrintf(char const*, ...)'

Bug: 70926074
Change-Id: Ic19f97cc5d1552be1bc77c9cec551cdbdd8259fb
Signed-off-by: Jaegeuk Kim <jaegeuk@google.com>
(cherry picked from commit 8a94acb741e10538d90db253b3bb937ef128676a)